In [2]:
# Import libraries
import numpy as np
import matplotlib.pyplot as plt

# Custom modules
import sys 
sys.path.append('../environments/')
import gridworlds
from dp import policy_evaluation


# Dynamic Programming

In [12]:
env = gridworlds.Grid_4x4()
state_space_n = len(env.state_space())
action_space_n = len(env.action_space())

## Policy evaluation

In [13]:
pi = np.ones([state_space_n, action_space_n]) / action_space_n   # equiprobable random policy
V = policy_evaluation(pi, env)
print('Policy evaluated after {} iterations:'.format(V[1]))
print(np.round(np.reshape(V[0], env.size), 4))

Policy evaluated after 263 iterations:
[[  0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.   0.]]
